spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gomendb
    username: gomendb
    password: gomendb
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

